# Generated by Django 5.0.7 on 2024-12-16 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerdetail',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.level'),
        ),
        migrations.AlterField(
            model_name='partnerdetail',
            name='partner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partnerdetail', to='partners.partner'),
        ),
        migrations.AlterField(
            model_name='partnerdetail',
            name='reakce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.reakce'),
        ),
        migrations.AlterField(
            model_name='partnerdetail',
            name='zpusob_osloveni',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.zpusobosloveni'),
        ),
        migrations.CreateModel(
            name='Osloveni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partner')),
                ('reakce', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.reakce')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('zpusob_osloveni', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.zpusobosloveni')),
            ],
        ),
    ]
