# Generated by Django 5.0.7 on 2024-12-16 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partnerdetail_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osloveni',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osloveni', to='partners.partner'),
        ),
    ]
