# Generated by Django 5.0.7 on 2024-12-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_alter_osloveni_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='osloveni',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
