# Generated by Django 5.0.7 on 2025-01-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_partner_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='jednatel',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
